### ISSUE TITLE
Letters on Flaps?

### ISSUE THREAD

**Issue by mattkerrison** [jp112sdl/SplitFlap#1]
Hey!

Just wondering how you're getting the letters on the polypropylene flaps? Are you applying the sticker packs that Scott Bezek uses, or are you printing onto the sheets before cutting them?

**Comment by jp112sdl** [comment]
I used self-adhesive labels (i.e. https://www.labelident.com/eb105x148ppwe.html)
The letters were cut with the laser cutter out of that labels.
4 letters fit on 1 sheet.
I put them in groups of 4 letters in SVG files here:https://github.com/jp112sdl/SplitFlap/tree/master/Letters
