### ISSUE TITLE
doubt in the code of esp8266

### ISSUE THREAD

**Issue by carlos-brito-123** [jp112sdl/SplitFlap#3]
hi congratulations for the project, I set up 4 modules I am a programming student, I want to understand the code of esp8266, not being able to understand where you connected the engine wires and how you send the words to the split flap? thanks.

**Comment by jp112sdl** [comment]
Hi,
sorry for the late reply.

The Mega2560, where all steppers are connected, uses `Serial2` (Pins 16 and 17) and the Esp8266, providing the web interface, uses a software serial on `D6` and `D7`
https://github.com/jp112sdl/SplitFlap/blob/a9b46231fd3726ffb9cbe177fb51e2d02c6dcdb5/Code/SplitFlap_ESP8266/SplitFlap_ESP8266.ino#L15

Everytime you see a `splitflapSerial.print(...)` in the code, a command is sent to the Mega2560.
Especially for displaying text, there is a small stack that can be filled with texts and a wait time between displaying the text
https://github.com/jp112sdl/SplitFlap/blob/master/Code/SplitFlap_ESP8266/SplitFlap_ESP8266.ino#L23-L26

Then, the text is sent within the `loop()`
https://github.com/jp112sdl/SplitFlap/blob/master/Code/SplitFlap_ESP8266/SplitFlap_ESP8266.ino#L597-L612
